### ISSUE TITLE
ECLIPSE_Karlo_Prior

### ISSUE THREAD

**Issue by apolinario** [eclipse-t2i/eclipse-inference#3]
Hello, in the README.md you mention `ECLIPSE-Community/ECLIPSE_Karlo_Prior` however this does not seem to be available @ Hugging Face. Do you have a pointer to where it is possible to find the Karlo (CLIP ViT-L/14) prior?

**Comment by Maitreyapatel** [comment]
Hi @apolinario, 

Closing the issue as this has been resolved. 
For others, we have released the checkpoint here: https://huggingface.co/ECLIPSE-Community/ECLIPSE_Karlo_Prior
